describe("User checkout an item Happy Path Testing", () => {
    const email = Cypress.env('HPTL_USER_EMAIL')
    const password = Cypress.env('HPTL_USER_PASSWORD')

    beforeEach(function () {
        cy.login(email, password).then(() => {
        cy.log('Logged in to Practice Software Testing')
    })
  })
    it('Successfully checkout item', () => {
        cy.get('[data-test="nav-categories"]').click()
        cy.get('[data-test="nav-hand-tools"]').click()
        cy.get('[data-test="product-01JJS97B6XDM0HEMF91NGYVAEE"]').click()
        cy.get('[data-test="add-to-cart"]').click()
        cy.wait(7000)
        cy.get('[data-test="nav-cart"]').click()
        cy.get('[data-test="product-title"]').contains('Combination Pliers')
        cy.get('[data-test="cart-total"]').contains('$14.15')
        cy.get('[data-test="proceed-1"]').click()
        cy.get('p.ng-star-inserted').contains('Hello Lei Test Atlas ESR, you are already logged in.')
        cy.get('[data-test="proceed-2"]').click()
        cy.wait(1000)
        cy.get('[data-test="proceed-3"]').click()
        cy.wait(1000)
        cy.get('label[for="payment-method"]').should('be.visible').click({ force: true }) //used this command as the element was hidden with another div
        cy.get('select').select('credit-card')
        cy.get('input#credit_card_number') 
            .scrollIntoView() 
            .should('be.visible')
            .type('4242-4242-4242-4242')
        cy.get('input#expiration_date') 
            .scrollIntoView() 
            .should('be.visible')
            .type('12/2025')
        cy.get('input#cvv') 
            .scrollIntoView() 
            .should('be.visible')
            .type('123')
        cy.get('input#card_holder_name') 
            .scrollIntoView() 
            .should('be.visible')
            .type('Atlas Test')
        cy.get('[data-test="finish"]').click()

        cy.get('.alert').contains('Payment was successful')
    })
})